### ISSUE TITLE
Too tight error boundaries on MSVC

### ISSUE THREAD

**Issue by nathanael-k** [cmm-20/a2#1]
Task 1.1 fails on my computer after compiling with the current MSVC.

Error is: 1.31414e-08
Delta Matrix:           0           0                              1.16516e-08
                               0            6.07747e-09           0

I am pretty sure my code is correct due to it's simplicity, and the values are too close to just be by chance.

**Comment by moritzge** [comment]
Choosing a higher error tolerance on the test should be fine. The tolerance might have been chosen to small for the tests to pass on all systems.
