### ISSUE TITLE
Task 1.2: parameter rbIdx

### ISSUE THREAD

**Issue by yannickkoster** [cmm-20/a2#10]
Hey everyone

What is the meaning of this parameter?

Thank you for reading and looking forward to your opinion.

**Comment by Hackempluf** [comment]
It stores the index of the rigid body.

Take a look at [KinematicEnergy.h](https://github.com/cmm-20/a2/blob/a2/src/rbSimLib/KinematicEnergy.h) to see an example usage of rbIdx. The two function `constraints` and `jacobian` use them.

**Comment by yannickkoster** [comment]
Thank you! The usage in KinematicEnergy.h let me understand.
