### ISSUE TITLE
Performance Issues on Linux

### ISSUE THREAD

**Issue by skell94** [cmm-20/a2#11]
So I'm having trouble with performance when running the app on my laptop which is running Ubuntu. The laptop is a Thinkpad T480s so I don't think it's a hardware problem. I tried the input from #9 and it helped a little but I am still having trouble with performance. The application is basically unresponsive as soon as I start the optimization. It takes several seconds to respond to input (if it does at all) and the frame rate drops below 1.

This is something I already noticed in the last exercise. It wasn't as extreme then but simple tasks like moving the heat map would freeze the application for several seconds and zooming was practically unusable.  

Does anybody have similar issues? Do I need to permanently switch to Windows for the apps to work properly?

**Comment by printablealice** [comment]
Hey!

Can you please confirm you’re running in Release mode and not Debug mode?

Thanks!
Jim

**Comment by printablealice** [comment]
On slower computers the optimization may take a while. I would be surprised
if it’s an OS issue. A quick thing you can do is hack the code a bit to
take say...5 steps of optimization, and then stop optimizing automatically.
The program should hang during those 5 steps, and then return control to
you when it’s done. It will be a bit annoying to work with, but it should l
get the job done.

Best,
Jim

**Comment by skell94** [comment]
Hi Jim, thanks for the fast response. To answer your question, yes I am running in release mode as the guy in #9 explained. This helped a little. 

In the mean time I have tried running the code on Windows on the same laptop (it's a dual boot) and you are right the OS doesn't make a difference, it is still very slow and unresponsive. Still, I don't consider this laptop to be particularly slow, it is fairly new, has a decent processor and I haven't had any performance issues with it until now. I guess these applications are just very demanding. Well, I'll just have to make do with what I have available. 

I think the problem is also that we use the `RandomMinimizer` because it takes a lot of iterations to actually get a somewhat good results as it just takes random guesses. Maybe it won't be as bad when using a more sophisitcated optimizer because it will converge more quickly.

Anyhow I am closing this because it seems to be a hardware limitation after all.
