### ISSUE TITLE
problem with makefile

### ISSUE THREAD

**Issue by PhilMoesch** [cmm-20/a2#12]
So I've been struggling for a while in trying to compiling my code, this is my current error :

You have called ADD_LIBRARY for library nanovg without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error: Cannot determine link language for target "nanovg".
CMake Error: CMake can not determine linker language for target: nanovg

thanks for any help

**Comment by nathanael-k** [comment]
did you maybe forget to get the sub-modules when doing the first git pull?
