### ISSUE TITLE
What to do in 2.2?

### ISSUE THREAD

**Issue by vyangETH** [cmm-20/a2#2]
Dear TAs,

In Task 2.2 we need to implement the evaluate function of the class MatchTrajectoryObjective. However it seems to be already implemented in line 20 of MechanismOptimizer.h. Is there anything other we can do than tuning the search region parameters or am I misunderstanding the task?

Thanks for your help!
Viviane

**Comment by tillns** [comment]
Would be interested in that as well.

**Comment by moritzge** [comment]
Well, it looks like for this task the solution made its way into the starter code repository :)
You can change the search domain for the Random Minimizer and report back the best solution it found.
