### ISSUE TITLE
Changing Rigidbody length does not update FixedJoint constraints

### ISSUE THREAD

**Issue by nathanael-k** [cmm-20/a2#3]
The app allows to update / change rigid body lengths, and the function setRigidBodyLength correctly updates the hingeJoints. However, it does not update the fixed joints.

This is evident if you increase or decrease the length of a link with a fixed point.

If you add the following in that function, it works:
```
for (auto& joint : fixed()) {
            if (joint.rbIdx == rbIdx) {
              if (joint.localPos[0] != 0) {
                double s = (joint.localPos[0] < 0) ? -1 : 1;
                joint.localPos[0] = s * length / 2;
              }
            
          }
        }
```

Note that there is also the scaleRigidBody function just above it, that can be fixed similarly. Or we could also define localPos of the constraints to be relative to the lenght.

**Comment by nathanael-k** [comment]
Maybe to add to that: the way the jansen mechanism is implemented, we have two fixed points constraint for link a and link l, each.
Right now, both are part of the link lengths we optimize over. as such, if we change the length of either link a or link l, we have constraints that cant be fulfilled simultaneously.

A possible solution would be to change the constraints of link a and l to only one single fixed point each, and the angle of each link. Is it okay to implement that, or does this go too far?

**Comment by moritzge** [comment]
Feel free to change the app to your liking :)
