### ISSUE TITLE
Task 1.1 test fails on 64-bit configuration

### ISSUE THREAD

**Issue by anilyaris** [cmm-20/a2#6]
When I initially built the project using CMake, I chose to create a 64-bit configuration, which caused test 1.1 to fail (other tests passed). When I built it with a 32-bit configuration, it passed as I expected. There's probably some weird floating point precision bug going on there, so I figured I could post this just as a heads-up for future assignments.

**Comment by rvin-r** [comment]
May I ask how exactly were you able to build it with a 32 bit config? I am currently facing the same issue I believe as the code should be right but 1.1 doesn't pass.

**Comment by lorenz-h** [comment]
I am also experiencing the same issue. My error is order e-7, therefore i assume that my code is working as it should. It seems feasible that the numerical computation of the gradient in the test is not sufficiently precise, or the error bounds are too tight

**Comment by anilyaris** [comment]
Sorry for the late reply. When configuring CMake (on Windows GUI), the default setting in my situation is Win32. I was setting it manually to x64 when I got the error, so I built it again without choosing the x64 option.
![Clipboard02](https://user-images.githubusercontent.com/29776001/77326564-44426280-6d1a-11ea-8173-2a756365be3b.png)

**Comment by moritzge** [comment]
For everyone with tests that _almost_ pass: You can relax the tolerances for tests to pass. For example for the test of task 1.1: https://github.com/cmm-20/a2/blob/cfa6e55f6410c905d03e816cccffb9a13c669903/src/tests/main.cpp#L57

You could change 1e-8 to e.g. 1e-6.
