### ISSUE TITLE
Task 1.1

### ISSUE THREAD

**Issue by ebonfalke** [cmm-20/a2#7]
For Task 1.1 I derived the following Jacobian:
        m(0,0) = 1.0;
        m(0,1) = 0.0;
        m(0, 2) = (drotationMatrix_dtheta(theta(x))* p)(0);
        
        m(1,0) = 0.0;
        m(1,1) = 1.0;
        m(1, 2) = (drotationMatrix_dtheta(theta(x))* p)(1);
which seems to be wrong. Could someone give me a tip where exactly I went wrong.

**Comment by nathanael-k** [comment]
check how far of you actually are from the FD solution. If you are very close, then your code is most probably correct.

**Comment by moritzge** [comment]
@ebonfalke were you able to resolve it?

**Comment by ebonfalke** [comment]
> @ebonfalke were you able to resolve it?

No, all the subsequebt tests pass so I believe that I have a similar problem as issue #1 but I don't get shown how far off my solution is so I'm not 100% sure.

**Comment by ebonfalke** [comment]
> > @ebonfalke were you able to resolve it?
> 
> No, all the subsequebt tests pass so I believe that I have a similar problem as issue #1 but I don't get shown how far off my solution is so I'm not 100% sure.

Ok, checked again with the higher tolerance mentioned in #1 and it passes.
