### ISSUE TITLE
Simulation & Optimization running slow

### ISSUE THREAD

**Issue by supernlogn** [cmm-20/a2#9]
The simulation and optimization parts are running too slow even for half the points.
The trajectory computation is very heavy.

Are there any suggestions (e.g. gcc flags) to make it faster?

**Comment by printablealice** [comment]
Hey!

Gotcha. Please just quickly confirm that you’re in Release mode and not
Debug while we take a look.

Thanks!
Jim

**Comment by supernlogn** [comment]
I was running the default cmake.
I thought it was using release flags, but now that you mentioned I searched it and I found that I should I specify -DCMAKE_BUILD_TYPE=Release 
It is getting faster.
However still it is slow and does not respond when "compute and update EE trajectory" is checked.

Thank you for your time.

**Comment by supernlogn** [comment]
I did it! 
I just needed a better computer :)

**Comment by printablealice** [comment]
Awesome! :)
